name: Macbook Dotfiles Installation

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: macos-14
    timeout-minutes: 20
    steps:
      - name: Clean up installed software
        run: |
          brew uninstall --ignore-dependencies --force $(brew list --formula)
          # brew uninstall --cask --force $(brew list --cask)
          brew uninstall --cask --force firefox google-chrome
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
      - name: Clone this repository
        uses: actions/checkout@v3
      - name: Install using Install Script
        run: chmod +x install.sh && ./install.sh
      - name: Verify using Verify Script
        run: chmod +x verify.zsh && zsh -c "source ~/.zshrc && $HOME/.dotfiles/verify.zsh"