name: Ubuntu Dotfiles Installation

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: homebrew/brew
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3
      - name: Install ZSH
        run: brew install zsh
      - name: Install using Install Script
        run: rm -rf $HOME/.gitconfig && chmod +x install.sh && ./install.sh
      - name: Verify using Verify Script
        run: chmod +x verify.zsh && zsh -c "source ~/.zshrc && $HOME/.dotfiles/verify.zsh"