name: Ubuntu Dotfiles Installation

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-install:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Get initial disk usage
        id: get_initial_usage
        run: ./tests/get_initial_disk_usage.sh

      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Install dotfiles
        run: ./install.sh

      # - name: Verifies dotfiles (ZSH)
      #   run: source ~/.zshrc && ./verify.zsh
      #   shell: /bin/zsh {0}
      #   env:
      #     ZSH_DISABLE_COMPFIX: true

      - name: Verifies dotfiles (BASH)
        run: source ~/.bashrc && ./verify.zsh

      - name: Check disk usage
        run: ./tests/check_disk_usage.sh
