name: Ubuntu Dotfiles Installation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ubuntu-install:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone this repository
        uses: actions/checkout@v4
      - name: Install dotfiles and verify
        uses: addnab/docker-run-action@v3
        with:
          image: homebrew/brew:latest
          options: -v ${{ github.workspace }}:/home/linuxbrew/.dotfiles
          run: |
            brew install zsh
            sudo chmod +x ~/.dotfiles/install.sh && ~/.dotfiles/install.sh
            sudo chmod +x ~/.dotfiles/verify.zsh && zsh -c "source ~/.zshrc && ~/.dotfiles/verify.zsh"