name: Ubuntu Dotfiles Installation

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-install:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Get initial disk usage
        id: get_initial_usage
        run: |
          initial_usage=$(df -h -B 1 | grep '/dev/root' | awk '{print $3}')
          echo "Initial disk usage: $initial_usage bytes"
          echo "initial_usage=$initial_usage" >> $GITHUB_ENV

      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Install dotfiles
        run: ./install.sh

      - name: Verifies dotfiles (BASH)
        run: source ~/.bashrc && ./verify.sh

      - name: Verifies dotfiles (ZSH)
        run: source ~/.zshrc && ./verify.sh
        shell: /bin/zsh {0}
        env:
          ZSH_DISABLE_COMPFIX: true

      - name: Check disk usage
        run: ./verify_disk_usage.sh
