name: Ubuntu Dotfiles Installation

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-install:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Get initial disk usage
        id: get_initial_usage
        run: |
          initial_usage=$(df -h -B 1 | grep '/dev/root' | awk '{print $3}')
          echo "Initial disk usage: $initial_usage bytes"
          echo "::set-output name=initial_usage::$initial_usage"

      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Install dotfiles
        run: ./install.sh

      # - name: Verifies dotfiles (ZSH)
      #   run: source ~/.zshrc && ./verify.zsh
      #   shell: /bin/zsh {0}
      #   env:
      #     ZSH_DISABLE_COMPFIX: true

      - name: Verifies dotfiles (BASH)
        run: source ~/.bashrc && ./verify.zsh

      - name: Get final disk usage
        id: get_final_usage
        run: |
          final_usage=$(df -h -B 1 | grep '/dev/root' | awk '{print $3}')
          echo "Final disk usage: $final_usage bytes"
          echo "::set-output name=final_usage::$final_usage"

      - name: Calculate disk usage change
        run: |
          initial_usage=${{ steps.get_initial_usage.outputs.initial_usage }}
          final_usage=${{ steps.get_final_usage.outputs.final_usage }}
          usage_change=$((final_usage - initial_usage))
          echo "Disk usage change: $usage_change bytes"