name: Ubuntu Dotfiles Installation

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu-install:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Get initial disk usage
        id: get_initial_usage
        run: |
          initial_usage=$(df -h -B 1 | grep '/dev/root' | awk '{print $3}')
          echo "Initial disk usage: $initial_usage bytes"
          echo "initial_usage=$initial_usage" >> $GITHUB_ENV

      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Install dotfiles
        run: ./install.sh

      # - name: Verifies dotfiles (ZSH)
      #   run: source ~/.zshrc && ./verify.zsh
      #   shell: /bin/zsh {0}
      #   env:
      #     ZSH_DISABLE_COMPFIX: true

      - name: Verifies dotfiles (BASH)
        run: source ~/.bashrc && ./verify.zsh

      - name: Check disk usage
        run: |
          final_usage=$(df -h -B 1 | grep '/dev/root' | awk '{print $3}')
          echo "Final disk usage: $final_usage bytes"
          initial_usage=${{ env.initial_usage }}
          usage_change_bytes=$((final_usage - initial_usage))
          usage_change_mb=$(echo "scale=2; $usage_change_bytes / (1024 * 1024)" | bc)
          echo "Disk usage change: $usage_change_mb MB"
          if (( $(echo "$usage_change_mb > 100" | bc -l) )); then
            echo "Error: Disk usage change exceeds 100MB. It is $usage_change_mb MB."
            exit 1
          fi