name: Ubuntu Dotfiles Installation

on:
  push:
    branches:
      - main

jobs:
  ubuntu-install:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone this repository
        uses: actions/checkout@v3
      - name: Install dotfiles and verify
        uses: addnab/docker-run-action@v3
        with:
          image: homebrew/brew:latest
          options: -v ${{ github.workspace }}://home/linuxbrew
          shell: bash
          run: |
            brew install zsh
            rm -rf $HOME/.gitconfig && sudo chmod +x install.sh && ./install.sh
            chmod +x verify.zsh && sudo zsh -c "source ~/.zshrc && $HOME/.dotfiles/verify.zsh"